# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html lang=\"en\">

<head>
    <meta charset=\"UTF-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\" />
    <title>Slot Car Data Logger</title>
    <link rel=\"stylesheet\" href=\"static/index.css\" />
    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"static/apple-touch-icon.png\">
    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"static/favicon-32x32.png\">
    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"static/favicon-16x16.png\">
    <link rel=\"manifest\" href=\"/site.webmanifest\">
    <!-- 
    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.0/chart.min.js\"></script>
    -->
    <script src=\"https://cdn.jsdelivr.net/npm/chart.js@3.3.2\"></script>
    <script src=\"https://cdn.jsdelivr.net/npm/luxon@1.27.0\"></script>
    <script src=\"https://cdn.jsdelivr.net/npm/chartjs-adapter-luxon@1.0.0\"></script>
    <script src=\"https://cdn.jsdelivr.net/npm/chartjs-plugin-streaming@2.0.0\"></script>
    
</head>

<body>
    <h1>Slot Car Data Logger</h1>
    <canvas id=\"theChart\" width=\"600\" height=\"400\"></canvas>
    <script src=\"static/index.js\"></script>
</body>

</html>"""
