CIRCUITPY_WIFI_SSID="FRITZ!Box 7530 YM"
CIRCUITPY_WIFI_PASSWORD="73119816833371417369"
#CIRCUITPY_WIFI_SSID="slot-car"
#CIRCUITPY_WIFI_PASSWORD="slot-car"
CIRCUITPY_WEB_INSTANCE_NAME=""
CIRCUITPY_WEB_API_PORT=80